--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -252,4 +252,4 @@
         with:
           tool: cargo-machete
       - name: cargo machete
-        run: cargo machete
+        run: cargo machete